name: Multi-Cloud CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Kubectl
        uses: azure/setup-kubectl@v3

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f k8s-manifests/
